[package]
rust-version.workspace = true
name = "sdkwork-api-search-standalone-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "HTTP API server process for SDKWork Search."

[[bin]]
name = "sdkwork-api-search-standalone-gateway"
path = "src/main.rs"


[lints]
workspace = true
[dependencies]
sdkwork-api-search-assembly.workspace = true
sdkwork-web-bootstrap = { workspace = true, features = ["sqlx"] }
tokio = { workspace = true }
tracing.workspace = true
anyhow.workspace = true
